"""Compatibility wrapper for V4 mechanism-context helpers."""

from src.mechanism_context import (
    ACTIVE_ROLES,
    BACKGROUND_ROLE,
    CANONICAL_CONTEXT_FAMILIES,
    CANONICAL_FAMILY_VERSION,
    COMPATIBLE,
    COMPATIBLE_SUPPORT_THRESHOLD,
    INCOMPATIBLE,
    INSUFFICIENT_CONTEXT,
    MECHANISM_COMPATIBILITY_VERSION,
    REQUIRED_CONTEXT_FIELDS,
    REVIEW_CANONICAL_CONTEXT_FAMILIES,
    TRANSMISSION_CONTEXT_VERSION,
    UNKNOWN_VALUES,
    CompatibilityDecision,
    canonical_family,
    mechanism_compatibility,
    mechanism_compatibility_with_family_review,
    support_diagnostics,
    support_diagnostics_with_family_review,
)

__all__ = [
    "ACTIVE_ROLES",
    "BACKGROUND_ROLE",
    "CANONICAL_CONTEXT_FAMILIES",
    "CANONICAL_FAMILY_VERSION",
    "COMPATIBLE",
    "COMPATIBLE_SUPPORT_THRESHOLD",
    "INCOMPATIBLE",
    "INSUFFICIENT_CONTEXT",
    "MECHANISM_COMPATIBILITY_VERSION",
    "REQUIRED_CONTEXT_FIELDS",
    "REVIEW_CANONICAL_CONTEXT_FAMILIES",
    "TRANSMISSION_CONTEXT_VERSION",
    "UNKNOWN_VALUES",
    "CompatibilityDecision",
    "canonical_family",
    "mechanism_compatibility",
    "mechanism_compatibility_with_family_review",
    "support_diagnostics",
    "support_diagnostics_with_family_review",
]
